import os
import shutil
from typing import Dict, Any, List, Optional
from jinja2 import Template
from app.core.stores import CaseContext
from app.core.config import Config, load_config
from app.models import GateResult, VerificationFinding, CitationFinding, FilingRecommendation

class Chronicle:
    def __init__(self, case_context: CaseContext):
        self.case_context = case_context
        self.config = load_config()

    def render_report(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]] = None, gate_result: Optional[GateResult] = None) -> str:
        # Default to HTML
        html_path = self.html_renderer(findings, citation_findings, gate_result)

        # Render others
        self.docx_renderer(findings, citation_findings, gate_result)
        self.pdf_renderer(html_path)

        return html_path

    def html_renderer(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]], gate_result: Optional[GateResult]) -> str:
        template_str = """
        <html>
        <head>
            <title>LegalMind Audit Report</title>
            <style>
                body { font-family: sans-serif; }
                .finding { border-bottom: 1px solid #ccc; padding: 10px; }
                .citation { border-bottom: 1px solid #eee; padding: 10px; }
                .gate { background-color: #f0f0f0; padding: 20px; border: 1px solid #999; margin-bottom: 20px; }
                .recommendation-CLEAR { color: green; font-weight: bold; }
                .recommendation-REVIEW_REQUIRED { color: orange; font-weight: bold; }
                .recommendation-DO_NOT_FILE { color: red; font-weight: bold; }
                .transparency { font-size: 0.8em; color: #666; margin-top: 50px; border-top: 1px solid #ccc; padding-top: 10px; }
            </style>
        </head>
        <body>
            <h1>LegalMind Audit Report</h1>

            {% if gate_result %}
            <div class="gate">
                <h2>Pre-Filing Gate</h2>
                <p>Recommendation: <span class="recommendation-{{ gate_result.filing_recommendation.name }}">{{ gate_result.filing_recommendation.value }}</span></p>
                <p>Risk Score: {{ gate_result.risk_score }}</p>
                <p>Timestamp: {{ gate_result.timestamp }}</p>
            </div>
            {% endif %}

            {% if findings %}
            <h2>Fact Verification</h2>
            {% for finding in findings %}
                <div class="finding">
                    <h3>Claim: {{ finding.claim_id }}</h3>
                    <p>Status: {{ finding.status.value }}</p>
                    <p>Confidence: {{ finding.confidence.value }}</p>
                    {% if export_raw and finding.quotes_with_provenance %}
                        <blockquote>{{ finding.quotes_with_provenance[0] }}</blockquote>
                    {% endif %}
                </div>
            {% endfor %}
            {% endif %}

            {% if citation_findings %}
            <h2>Citation Verification</h2>
            {% for citation in citation_findings %}
                <div class="citation">
                    <h3>{{ citation.citation_text }}</h3>
                    <p>Status: {{ citation.status.value }}</p>
                    <p>Case: {{ citation.case_details.name }} ({{ citation.case_details.date }})</p>
                </div>
            {% endfor %}
            {% endif %}

            <div class="transparency">
                <h3>System Transparency</h3>
                {% if gate_result %}
                <p>Engine Version: {{ gate_result.config_snapshot.engine_version }}</p>
                <p>Model: {{ gate_result.config_snapshot.model }}</p>
                <p>Retrieval Mode: {{ gate_result.config_snapshot.retrieval_mode }}</p>
                {% else %}
                <p>Engine Version: 3.0</p>
                <p>Model Provider: {{ config.LLM_PROVIDER }}</p>
                {% endif %}
                <p>Raw Evidence Export: {{ config.EXPORT_RAW_EVIDENCE }}</p>
                <p>This report was generated by LegalMind. Verify all findings independently.</p>
            </div>
        </body>
        </html>
        """
        template = Template(template_str)
        html = template.render(
            findings=findings,
            citation_findings=citation_findings,
            gate_result=gate_result,
            config=self.config,
            export_raw=self.config.EXPORT_RAW_EVIDENCE
        )

        report_path = os.path.join(self.case_context.base_path, "report.html")
        with open(report_path, "w") as f:
            f.write(html)
        return report_path

    def docx_renderer(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]], gate_result: Optional[GateResult]):
        import docx
        doc = docx.Document()
        doc.add_heading("LegalMind Audit Report", 0)

        if gate_result:
            doc.add_heading("Pre-Filing Gate", 1)
            doc.add_paragraph(f"Recommendation: {gate_result.filing_recommendation.value}")
            doc.add_paragraph(f"Risk Score: {gate_result.risk_score}")
            doc.add_paragraph(f"Timestamp: {gate_result.timestamp}")

        if findings:
            doc.add_heading("Fact Verification", 1)
            for finding in findings:
                doc.add_heading(f"Claim: {finding.claim_id}", 2)
                doc.add_paragraph(f"Status: {finding.status.value}")
                doc.add_paragraph(f"Confidence: {finding.confidence.value}")
                if self.config.EXPORT_RAW_EVIDENCE and finding.quotes_with_provenance:
                    doc.add_paragraph(finding.quotes_with_provenance[0], style="Quote")

        if citation_findings:
            doc.add_heading("Citation Verification", 1)
            for citation in citation_findings:
                doc.add_paragraph(f"{citation.citation_text} - {citation.status.value}")

        # Transparency
        doc.add_heading("System Transparency", 1)
        doc.add_paragraph(f"Model Provider: {self.config.LLM_PROVIDER}")
        doc.add_paragraph(f"Raw Evidence Export: {self.config.EXPORT_RAW_EVIDENCE}")

        path = os.path.join(self.case_context.base_path, "report.docx")
        doc.save(path)
        return path

    def pdf_renderer(self, html_path: str):
        from weasyprint import HTML
        path = os.path.join(self.case_context.base_path, "report.pdf")
        HTML(filename=html_path).write_pdf(path)
        return path

    def executive_summarizer(self, findings: Any): pass
    def quality_dashboard(self): pass
    def transparency_writer(self): pass
    def media_indexer(self): pass
    def timestamp_service(self): pass
