import os
import json
import shutil
import docx
from typing import Dict, Any, List, Optional
from jinja2 import Template
from app.core.stores import CaseContext
from app.core.config import Config, load_config
from app.models import GateResult, VerificationFinding, CitationFinding, FilingRecommendation

class Chronicle:
    def __init__(self, case_context: CaseContext):
        self.case_context = case_context
        self.config = load_config()

    def render_report(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]] = None, gate_result: Optional[GateResult] = None) -> str:
        # Default to HTML
        html_path = self.html_renderer(findings, citation_findings, gate_result)

        # Render others
        self.docx_renderer(findings, citation_findings, gate_result)
        self.pdf_renderer(html_path)

        return html_path

    def html_renderer(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]], gate_result: Optional[GateResult]) -> str:
        template_str = """
        <html>
        <head>
            <title>LegalMind Audit Report</title>
            <style>
                body { font-family: sans-serif; }
                .finding { border-bottom: 1px solid #ccc; padding: 10px; }
                .citation { border-bottom: 1px solid #eee; padding: 10px; }
                .gate { background-color: #f0f0f0; padding: 20px; border: 1px solid #999; margin-bottom: 20px; }
                .recommendation-CLEAR { color: green; font-weight: bold; }
                .recommendation-REVIEW_REQUIRED { color: orange; font-weight: bold; }
                .recommendation-DO_NOT_FILE { color: red; font-weight: bold; }
                .transparency { font-size: 0.8em; color: #666; margin-top: 50px; border-top: 1px solid #ccc; padding-top: 10px; }
            </style>
        </head>
        <body>
            <h1>LegalMind Audit Report</h1>

            {% if gate_result %}
            <div class="gate">
                <h2>Pre-Filing Gate</h2>
                <p>Recommendation: <span class="recommendation-{{ gate_result.filing_recommendation.name }}">{{ gate_result.filing_recommendation.value }}</span></p>
                <p>Risk Score: {{ gate_result.risk_score }}</p>
                <p>Timestamp: {{ gate_result.timestamp }}</p>
            </div>
            {% endif %}

            {% if findings %}
            <h2>Fact Verification</h2>
            {% for finding in findings %}
                <div class="finding">
                    <h3>Claim: {{ finding.claim_id }}</h3>
                    <p>Status: {{ finding.status.value }}</p>
                    <p>Confidence: {{ finding.confidence.value }}</p>
                    {% if export_raw and finding.quotes_with_provenance %}
                        <blockquote>{{ finding.quotes_with_provenance[0] }}</blockquote>
                    {% endif %}
                </div>
            {% endfor %}
            {% endif %}

            {% if citation_findings %}
            <h2>Citation Verification</h2>
            {% for citation in citation_findings %}
                <div class="citation">
                    <h3>{{ citation.citation_text }}</h3>
                    <p>Status: {{ citation.status.value }}</p>
                    <p>Case: {{ citation.case_details.name }} ({{ citation.case_details.date }})</p>
                </div>
            {% endfor %}
            {% endif %}

            <div class="transparency">
                <h3>System Transparency</h3>
                {% if gate_result %}
                <p>Engine Version: {{ gate_result.config_snapshot.engine_version }}</p>
                <p>Model: {{ gate_result.config_snapshot.model }}</p>
                <p>Retrieval Mode: {{ gate_result.config_snapshot.retrieval_mode }}</p>
                {% else %}
                <p>Engine Version: 3.0</p>
                <p>Model Provider: {{ config.LLM_PROVIDER }}</p>
                {% endif %}
                <p>Raw Evidence Export: {{ config.EXPORT_RAW_EVIDENCE }}</p>
                <p>This report was generated by LegalMind. Verify all findings independently.</p>
            </div>
        </body>
        </html>
        """
        template = Template(template_str)
        html = template.render(
            findings=findings,
            citation_findings=citation_findings,
            gate_result=gate_result,
            config=self.config,
            export_raw=self.config.EXPORT_RAW_EVIDENCE
        )

        report_path = os.path.join(self.case_context.base_path, "report.html")
        with open(report_path, "w") as f:
            f.write(html)
        return report_path

    def docx_renderer(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]], gate_result: Optional[GateResult]):
        doc = docx.Document()
        doc.add_heading("LegalMind Audit Report", 0)

        if gate_result:
            doc.add_heading("Pre-Filing Gate", 1)
            doc.add_paragraph(f"Recommendation: {gate_result.filing_recommendation.value}")
            doc.add_paragraph(f"Risk Score: {gate_result.risk_score}")
            doc.add_paragraph(f"Timestamp: {gate_result.timestamp}")

        if findings:
            doc.add_heading("Fact Verification", 1)
            for finding in findings:
                doc.add_heading(f"Claim: {finding.claim_id}", 2)
                doc.add_paragraph(f"Status: {finding.status.value}")
                doc.add_paragraph(f"Confidence: {finding.confidence.value}")
                if self.config.EXPORT_RAW_EVIDENCE and finding.quotes_with_provenance:
                    doc.add_paragraph(finding.quotes_with_provenance[0], style="Quote")

        if citation_findings:
            doc.add_heading("Citation Verification", 1)
            for citation in citation_findings:
                doc.add_paragraph(f"{citation.citation_text} - {citation.status.value}")

        # Transparency
        doc.add_heading("System Transparency", 1)
        doc.add_paragraph(f"Model Provider: {self.config.LLM_PROVIDER}")
        doc.add_paragraph(f"Raw Evidence Export: {self.config.EXPORT_RAW_EVIDENCE}")

        path = os.path.join(self.case_context.base_path, "report.docx")
        doc.save(path)
        return path

    def pdf_renderer(self, html_path: str):
        from weasyprint import HTML
        path = os.path.join(self.case_context.base_path, "report.pdf")
        HTML(filename=html_path).write_pdf(path)
        return path

    def executive_summarizer(self, findings: Any): pass

    def quality_dashboard(self, findings: List[VerificationFinding], citation_findings: Optional[List[CitationFinding]] = None, gate_result: Optional[GateResult] = None) -> str:
        # Calculate stats
        total_claims = len(findings)
        supported_claims = sum(1 for f in findings if f.status.value == "Supported")
        partially_supported_claims = sum(1 for f in findings if f.status.value == "Partially Supported")
        not_supported_claims = sum(1 for f in findings if f.status.value == "Not Supported")
        contradicted_claims = sum(1 for f in findings if f.status.value == "Contradicted")
        review_claims = sum(1 for f in findings if f.status.value == "Needs Manual Review")

        total_citations = len(citation_findings) if citation_findings else 0
        verified_citations = sum(1 for c in citation_findings if c.status.value == "Verified") if citation_findings else 0
        not_found_citations = sum(1 for c in citation_findings if c.status.value == "Not Found") if citation_findings else 0

        stats = {
            "total_claims": total_claims,
            "supported_claims": supported_claims,
            "partially_supported_claims": partially_supported_claims,
            "not_supported_claims": not_supported_claims,
            "contradicted_claims": contradicted_claims,
            "review_claims": review_claims,
            "total_citations": total_citations,
            "verified_citations": verified_citations,
            "not_found_citations": not_found_citations,
            "risk_score": gate_result.risk_score if gate_result else 0.0,
            "filing_recommendation": gate_result.filing_recommendation.value if gate_result else "N/A"
        }

        # Save JSON
        json_path = os.path.join(self.case_context.base_path, "dashboard.json")
        with open(json_path, "w") as f:
            json.dump(stats, f, indent=2)

        # Render HTML
        template_str = """
        <html>
        <head>
            <title>LegalMind Quality Dashboard</title>
            <style>
                body { font-family: sans-serif; background-color: #f4f4f9; color: #333; }
                .container { width: 80%; margin: 0 auto; padding: 20px; }
                .card { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
                h1, h2 { color: #2c3e50; }
                .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; }
                .stat-box { background: #eef2f3; padding: 15px; border-radius: 5px; text-align: center; }
                .stat-value { font-size: 2em; font-weight: bold; color: #3498db; }
                .stat-label { font-size: 0.9em; color: #7f8c8d; }
                .risk-score { font-size: 2.5em; font-weight: bold; color: {{ 'red' if stats.risk_score > 50 else 'orange' if stats.risk_score > 20 else 'green' }}; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Quality Dashboard</h1>

                <div class="card">
                    <h2>Overall Risk</h2>
                    <div style="text-align: center;">
                        <div>Risk Score: <span class="risk-score">{{ stats.risk_score }}</span></div>
                        <p>Recommendation: <strong>{{ stats.filing_recommendation }}</strong></p>
                    </div>
                </div>

                <div class="card">
                    <h2>Claim Verification</h2>
                    <div class="stat-grid">
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.total_claims }}</div>
                            <div class="stat-label">Total Claims</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.supported_claims }}</div>
                            <div class="stat-label">Supported</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.contradicted_claims }}</div>
                            <div class="stat-label">Contradicted</div>
                        </div>
                         <div class="stat-box">
                            <div class="stat-value">{{ stats.not_supported_claims }}</div>
                            <div class="stat-label">Not Supported</div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h2>Citation Analysis</h2>
                     <div class="stat-grid">
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.total_citations }}</div>
                            <div class="stat-label">Total Citations</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.verified_citations }}</div>
                            <div class="stat-label">Verified</div>
                        </div>
                        <div class="stat-box">
                            <div class="stat-value">{{ stats.not_found_citations }}</div>
                            <div class="stat-label">Not Found</div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
        </html>
        """
        template = Template(template_str)
        html = template.render(stats=stats)

        html_path = os.path.join(self.case_context.base_path, "dashboard.html")
        with open(html_path, "w") as f:
            f.write(html)

        return html_path

    def transparency_writer(self): pass
    def media_indexer(self): pass
    def timestamp_service(self): pass
